### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by janareddyc7** [techblitzdev/TechBlitz#333]
Hey i wanted to contribute to this project but i found a issue on the env files is there any env variables to setup

**Comment by Logannford** [comment]
hey @janareddyc7 ! It appears I forgot to add a `.env.example`. I will add one and get back to you once ready :)

**Comment by Logannford** [comment]
hey @janareddyc7 ! I have just added the `.env.example` file. If you need anymore help setting up, please don't hesitate to reach out!

**Comment by janareddyc7** [comment]
thanks
